// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCrmZ1-fZxwXxCpuCrRzJj8y8wjDMMMoY',
    appId: '1:112671406741:android:bbcdb207858d92b0dbb99c',
    messagingSenderId: '112671406741',
    projectId: 'whatsapp-clone-2eca9',
    storageBucket: 'whatsapp-clone-2eca9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7P1I0JOBcCDrwajE4JyUpx1Yc4-LxlKQ',
    appId: '1:112671406741:ios:61cbdaa2ee822356dbb99c',
    messagingSenderId: '112671406741',
    projectId: 'whatsapp-clone-2eca9',
    storageBucket: 'whatsapp-clone-2eca9.appspot.com',
    iosClientId: '112671406741-ci3ej176u9u8a109kpe4m1torq2u3hcs.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappFlutterUi',
  );
}
